pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
rootProject.name = "OMaMul"
include ':app'
include ':core'
include ':core:data'
include ':core:database'
include ':core:domain'
include ':core:ui'
include ':core:common'
include ':feature-water'
include ':feature-common'
include ':feature-common:init'
include ':feature-water:alarm'
include ':feature-water:cup'
include ':feature-water:home'
include ':feature-water:record'
include ':feature-water:setting'
include ':feature-common:base'
include ':core:navigation'
include ':core:datastore'
include ':core:alarmnoti'
include ':core:firebase'
