plugins {
    alias libs.plugins.android.library
    alias libs.plugins.jetbrains.kotlin.android
    alias libs.plugins.kotlin.compose
    alias libs.plugins.hilt
    alias libs.plugins.navigation.safeargs
    id 'kotlin-kapt'
}

android {
    namespace 'com.tkw.alarm'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled true // material-icons-extended 번들 사용 시 필수
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        dataBinding = true
        viewBinding = true
        compose = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
}

dependencies {
    implementation project(':core:domain')
    implementation project(':core:common')
    implementation project(':core:ui')
    implementation project(':core:alarmnoti')
    implementation project(':core:navigation')
    implementation project(':feature-common:base')

    implementation libs.androidx.core
    implementation libs.androidx.appcompat
    implementation libs.android.material
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso

    implementation libs.androidx.navigation.fragment
    implementation libs.androidx.navigation.ui

    //hiltNavGraphViewModels
    implementation libs.androidx.hilt.navigation.fragment

    //Flow.asLiveData
    implementation libs.androidx.lifecycle.livedata

    //by viewModels
    implementation libs.androidx.activity.ktx

    //by activityViewModels
    implementation libs.androidx.fragment.ktx

    //hilt
    implementation libs.hilt
    // KAPT(Kotlin Annotation Processing Tools), 어노테이션 사용, annotationProcessor의 대체
    kapt libs.hilt.compiler

    //compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest
}

kapt {
    correctErrorTypes true
}