[versions]
core-ktx = "1.13.1"
appcompat = "1.6.1"
material = "1.12.0"
constraintlayout = "2.1.4"
junit = "4.13.2"
ext-junit = "1.2.1"
espresso-core = "3.6.1"
navigation-fragment-ktx = "2.7.7"
navigation-ui-ktx = "2.7.7"
core-splashscreen = "1.0.1"
coroutines = "1.8.1"

activity-ktx = "1.9.0"
fragment-ktx = "1.8.1"
lifecycle-livedata-ktx = "2.8.3"
lifecycle-viewmodel-ktx = "2.8.3"

retrofit = "2.11.0"
converter-gson = "2.11.0"
okhttp = "4.12.0"
logging-interceptor = "4.12.0"

realm-library-base = "2.3.0"
realm-library-sync = "2.3.0"

mp-android-chart = "v3.1.0"

android-application = "8.4.2"
android-library = "8.4.2"
kotlin = "2.0.20"
navigation-safeargs = "2.7.7"
realm-kotlin = "2.3.0"

hilt = "2.51.1"
hilt-navigation = "1.2.0"

datastore-preferences = "1.1.1"

work = "2.9.0"

google-services = "4.4.2"
firebase-bom = "33.2.0"
play-services-auth = "21.2.0"
credentials = "1.2.2"
credentials-play-services-auth = "1.2.2"
googleid = "1.1.1"

glide = "4.16.0"
lottie = "6.5.0"

# Jetpack Compose
compose-bom = "2024.09.00"
activity-compose = "1.9.0"

[libraries]
androidx-core = {module="androidx.core:core-ktx", version.ref="core-ktx"}
androidx-appcompat = {module="androidx.appcompat:appcompat", version.ref="appcompat"}
android-material = {module="com.google.android.material:material", version.ref="material"}
androidx-constraintlayout = {module="androidx.constraintlayout:constraintlayout", version.ref="constraintlayout"}
junit = {module="junit:junit", version.ref="junit"}
androidx-test-junit = {module="androidx.test.ext:junit", version.ref="ext-junit"}
androidx-test-espresso = {module="androidx.test.espresso:espresso-core", version.ref="espresso-core"}

androidx-navigation-fragment = {module="androidx.navigation:navigation-fragment-ktx", version.ref="navigation-fragment-ktx"}
androidx-navigation-ui = {module="androidx.navigation:navigation-ui-ktx", version.ref="navigation-ui-ktx"}
androidx-splash = {module="androidx.core:core-splashscreen", version.ref="core-splashscreen"}

androidx-activity-ktx = {module="androidx.activity:activity-ktx", version.ref="activity-ktx"}
androidx-fragment-ktx = {module="androidx.fragment:fragment-ktx", version.ref="fragment-ktx"}
androidx-lifecycle-livedata = {module="androidx.lifecycle:lifecycle-livedata-ktx", version.ref="lifecycle-livedata-ktx"}
androidx-lifecycle-viewmodel = {module="androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref="lifecycle-viewmodel-ktx"}

retrofit2-retrofit = {module="com.squareup.retrofit2:retrofit", version.ref="retrofit"}
retrofit2-converter-gson = {module="com.squareup.retrofit2:converter-gson", version.ref="converter-gson"}
okhttp3-okhttp = {module="com.squareup.okhttp3:okhttp", version.ref="okhttp"}
okhttp3-logging-interceptor = {module="com.squareup.okhttp3:logging-interceptor", version.ref="logging-interceptor"}

realm-kotlin-library-base = {module="io.realm.kotlin:library-base", version.ref="realm-library-base"}
realm-kotlin-library-sync = {module="io.realm.kotlin:library-sync", version.ref="realm-library-sync"}

android-chart = {module="com.github.PhilJay:MPAndroidChart", version.ref="mp-android-chart"}

kotlinx-coroutines = {module="org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref="coroutines"}

hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt_compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore-preferences"}

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics"}
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "play-services-auth" }

credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials-play-services-auth" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }

# Jetpack Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hilt-navigation" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }
androidx-compose-material-icons-extend = { module = "androidx.compose.material:material-icons-extended" }

[plugins]
android-application = { id="com.android.application", version.ref="android-application"}
android-library = {id="com.android.library", version.ref="android-library"}
jetbrains-kotlin-android = {id="org.jetbrains.kotlin.android", version.ref="kotlin"}
jetbrains-kotlin-jvm = {id="org.jetbrains.kotlin.jvm", version.ref="kotlin"}
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-safeargs = {id="androidx.navigation.safeargs.kotlin", version.ref="navigation-safeargs"}
realm-kotlin = {id="io.realm.kotlin", version.ref="realm-kotlin"}

hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }

[bundles]
retrofit = ['retrofit2-retrofit', 'retrofit2-converter-gson', 'okhttp3-okhttp', 'okhttp3-logging-interceptor']
compose = [
    "androidx-activity-compose",
    "androidx-compose-foundation",
    "androidx-compose-ui",
    "androidx-compose-ui-graphics",
    "androidx-compose-ui-tooling-preview",
    "androidx-compose-material3",
    "androidx-hilt-navigation-compose",
    "androidx-compose-material-icons-extend"
]
