plugins {
    alias libs.plugins.android.library
    alias libs.plugins.jetbrains.kotlin.android
    alias libs.plugins.hilt
    alias libs.plugins.kotlin.compose
    id 'kotlin-kapt'
}

android {
    namespace 'com.tkw.setting'
    compileSdk 34

    defaultConfig {
        minSdk 26
        targetSdk 34

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    flavorDimensions = ["app-dev"]
    productFlavors {
        prod {
            dimension "app-dev"
        }

        dev {
            dimension "app-dev"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    buildFeatures {
        compose = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
}

dependencies {
    implementation project(':core:common')
    implementation project(':core:domain')
    implementation project(':core:ui')
    implementation project(':core:navigation')
    implementation project(':core:firebase')
    implementation project(':feature-common:base')
    implementation project(':feature-water:home')

    implementation libs.androidx.core
    implementation libs.androidx.appcompat
    implementation libs.android.material
    implementation libs.androidx.constraintlayout
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso


    //Flow.asLiveData
    implementation libs.androidx.lifecycle.livedata

    //by viewModels
    implementation libs.androidx.activity.ktx


    //hilt
    implementation libs.hilt
    implementation libs.androidx.hilt.navigation.compose
    // KAPT(Kotlin Annotation Processing Tools), 어노테이션 사용, annotationProcessor의 대체
    kapt libs.hilt.compiler

    // compose
    implementation platform(libs.androidx.compose.bom)
    implementation libs.bundles.compose
    debugImplementation libs.androidx.compose.ui.tooling
    debugImplementation libs.androidx.compose.ui.test.manifest

    //glide
    implementation libs.glide

    //AuthorizationClient
    implementation libs.play.services.auth

}

kapt {
    correctErrorTypes true
}