plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.jetbrains.kotlin.android)
    alias libs.plugins.hilt
    alias libs.plugins.ksp
}

android {
    namespace 'com.tkw.firebase'
    compileSdk 34

    defaultConfig {
        minSdk 26

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
    }

    flavorDimensions = ["app-dev"]
    productFlavors {
        prod {
            dimension "app-dev"
        }

        dev {
            dimension "app-dev"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    sourceSets {
        dev {
            res.srcDirs = ['src/dev/res']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }
}

dependencies {
    implementation project(':core:domain')
    implementation project(':core:alarmnoti')

    implementation libs.androidx.core
    implementation libs.androidx.appcompat
    implementation libs.android.material
    testImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.androidx.test.espresso

    //hilt
    implementation libs.hilt
    // KAPT(Kotlin Annotation Processing Tools), 어노테이션 사용, annotationProcessor의 대체
    ksp libs.hilt.compiler

    //firebase
    implementation platform(libs.firebase.bom)
    implementation libs.firebase.analytics
    implementation libs.firebase.auth.ktx
    implementation libs.play.services.auth
    implementation("com.google.firebase:firebase-storage")

    //Credential Manager
    implementation libs.credentials
    implementation libs.credentials.play.services.auth
    implementation libs.googleid

    //Google Drive
    implementation 'com.google.api-client:google-api-client:2.0.0'
//    implementation 'com.google.http-client:google-http-client-gson:1.42.1'
    implementation 'com.google.oauth-client:google-oauth-client-jetty:1.34.1'
    implementation 'com.google.apis:google-api-services-drive:v3-rev20220815-2.0.0'
    implementation 'com.google.auth:google-auth-library-oauth2-http:1.24.0'
}